[package]
name = "ch02-a-tour-of-rust"
version = "0.1.0"
edition = "2024"
description = "Rust概览"

[lib]
name = "ch02"
path = "src/lib.rs"

[dependencies]
crossbeam = "0.8.4"
image = "0.13.0"
num = "0.4.3"
